// Усі картки, згруповані по темах. uk = українська, nl = нідерландська, ex = приклад речення.
window.DECKS = [
  {
    id: "greetings",
    title: "Привітання",
    nlTitle: "Begroetingen",
    cards: [
      { uk: "привіт", nl: "hoi", ex: "Hoi Lisa, hoe gaat het?" },
      { uk: "добрий день", nl: "goedemiddag", ex: "Goedemiddag meneer Bakker." },
      { uk: "добрий вечір", nl: "goedenavond", ex: "Goedenavond mevrouw Jansen." },
      { uk: "дорогий / дорога", nl: "beste", ex: "Beste docent." },
      { uk: "шановний пане", nl: "geachte meneer", ex: "Geachte meneer De Vries." },
      { uk: "шановна пані", nl: "geachte mevrouw", ex: "Geachte mevrouw Bakker." },
      { uk: "як справи", nl: "hoe gaat het", ex: "Hoe gaat het met je?" },
      { uk: "сподіваюсь, що у вас все добре", nl: "ik hoop dat het goed met u gaat", ex: "Ik hoop dat het goed met u gaat." },
      { uk: "дякую за e-mail", nl: "bedankt voor uw e-mail", ex: "Bedankt voor uw e-mail." },
      { uk: "дякую за повідомлення", nl: "bedankt voor je bericht", ex: "Bedankt voor je bericht." },
    ],
  },
  {
    id: "letter-end",
    title: "Закінчення листа",
    nlTitle: "Afsluiten van een brief",
    cards: [
      { uk: "з повагою", nl: "met vriendelijke groet", ex: "Met vriendelijke groet, Anna." },
      { uk: "вітання", nl: "groeten", ex: "Groeten, Ahmed." },
      { uk: "до завтра", nl: "tot morgen", ex: "Tot morgen op school." },
      { uk: "до зустрічі", nl: "tot ziens", ex: "Tot ziens." },
      { uk: "гарного дня", nl: "fijne dag", ex: "Fijne dag verder." },
      { uk: "гарного вечора", nl: "fijne avond", ex: "Fijne avond." },
      { uk: "бувай", nl: "doei", ex: "Doei en tot snel." },
      { uk: "обіймаю", nl: "liefs", ex: "Liefs, Maria." },
      { uk: "чекаю на вашу відповідь", nl: "ik hoor graag van u", ex: "Ik hoor graag van u." },
      { uk: "чекаю на твою відповідь", nl: "ik hoor graag van je", ex: "Ik hoor graag van je." },
    ],
  },
  {
    id: "wishes",
    title: "Вітання та побажання",
    nlTitle: "Felicitaties en wensen",
    cards: [
      { uk: "вітаю", nl: "gefeliciteerd", ex: "Gefeliciteerd met je nieuwe woning." },
      { uk: "вітаю з днем народження", nl: "gefeliciteerd met je verjaardag", ex: "Gefeliciteerd met je verjaardag." },
      { uk: "вітаю з новою роботою", nl: "gefeliciteerd met je nieuwe baan", ex: "Gefeliciteerd met je nieuwe baan." },
      { uk: "вітаю з народженням дитини", nl: "gefeliciteerd met de geboorte van jullie baby", ex: "Gefeliciteerd met de geboorte van jullie baby." },
      { uk: "одужуй", nl: "beterschap", ex: "Beterschap Karim." },
      { uk: "бажаю успіху", nl: "veel succes", ex: "Veel succes met je examen." },
      { uk: "гарної подорожі", nl: "goede reis", ex: "Goede reis naar Spanje." },
      { uk: "ласкаво просимо", nl: "welkom", ex: "Welkom in Nederland." },
      { uk: "веселих свят", nl: "fijne feestdagen", ex: "Fijne feestdagen voor jou en je familie." },
    ],
  },
  {
    id: "letter-phrases",
    title: "Найважливіші фрази для листів",
    nlTitle: "Belangrijke zinnen voor brieven",
    cards: [
      { uk: "я пишу тому що", nl: "ik schrijf omdat", ex: "Ik schrijf omdat ik ziek ben." },
      { uk: "я надсилаю цей e-mail", nl: "ik stuur deze e-mail", ex: "Ik stuur deze e-mail naar mijn baas." },
      { uk: "у мене є проблема", nl: "ik heb een probleem", ex: "Ik heb een probleem met mijn laptop." },
      { uk: "я не можу прийти", nl: "ik kan niet komen", ex: "Ik kan vandaag niet komen." },
      { uk: "я запізнююсь", nl: "ik kom te laat", ex: "Ik kom morgen te laat." },
      { uk: "мені шкода", nl: "het spijt me", ex: "Het spijt me dat ik niet kan komen." },
      { uk: "мої вибачення", nl: "mijn excuses", ex: "Mijn excuses voor het probleem." },
      { uk: "чи можу я", nl: "mag ik", ex: "Mag ik jouw laptop lenen?" },
      { uk: "чи можете ви", nl: "kunt u", ex: "Kunt u mij helpen?" },
      { uk: "чи хочеш ти", nl: "wil je", ex: "Wil je morgen komen?" },
      { uk: "я хотів би", nl: "ik wil graag", ex: "Ik wil graag Nederlands leren." },
      { uk: "я повинен", nl: "ik moet", ex: "Ik moet morgen werken." },
      { uk: "я хочу скасувати", nl: "ik wil afzeggen", ex: "Ik wil de afspraak afzeggen." },
      { uk: "я зателефоную пізніше", nl: "ik bel later", ex: "Ik bel u later vandaag." },
      { uk: "я поверну це завтра", nl: "ik geef het morgen terug", ex: "Ik geef de laptop morgen terug." },
      { uk: "чи можемо ми зустрітися", nl: "kunnen we afspreken", ex: "Kunnen we morgen afspreken?" },
      { uk: "я маю зустріч", nl: "ik heb een afspraak", ex: "Ik heb morgen een afspraak." },
      { uk: "мені потрібна допомога", nl: "ik heb hulp nodig", ex: "Ik heb hulp nodig met mijn huiswerk." },
      { uk: "дякую за допомогу", nl: "bedankt voor de hulp", ex: "Bedankt voor de hulp." },
    ],
  },
  {
    id: "school",
    title: "Школа та навчання",
    nlTitle: "School en studie",
    cards: [
      { uk: "школа", nl: "school", ex: "Mijn school is groot." },
      { uk: "курс", nl: "cursus", ex: "Ik volg een cursus Nederlands." },
      { uk: "урок", nl: "les", ex: "Vandaag heb ik les." },
      { uk: "викладач", nl: "docent", ex: "Mijn docent is aardig." },
      { uk: "студент", nl: "student", ex: "De student leert Nederlands." },
      { uk: "одногрупник", nl: "studiegenoot", ex: "Lisa is mijn studiegenoot." },
      { uk: "домашнє завдання", nl: "huiswerk", ex: "Het huiswerk is moeilijk." },
      { uk: "екзамен", nl: "examen", ex: "Morgen heb ik examen." },
      { uk: "тест", nl: "toets", ex: "Ik maak de toets volgende week." },
      { uk: "оцінка", nl: "cijfer", ex: "Ik heb een goed cijfer." },
      { uk: "мовна школа", nl: "taalschool", ex: "De taalschool is dichtbij." },
      { uk: "рівень", nl: "niveau", ex: "Ik leer op niveau A2." },
      { uk: "слухання", nl: "luisteren", ex: "Luisteren is moeilijk." },
      { uk: "читання", nl: "lezen", ex: "Lezen is belangrijk." },
      { uk: "письмо", nl: "schrijven", ex: "Schrijven vind ik moeilijk." },
      { uk: "говоріння", nl: "spreken", ex: "Ik wil beter spreken." },
      { uk: "комп'ютер", nl: "computer", ex: "Ik werk op de computer." },
      { uk: "ноутбук", nl: "laptop", ex: "Mijn laptop is kapot." },
      { uk: "інтернет", nl: "internet", ex: "Mijn internet werkt niet." },
      { uk: "навчатися", nl: "leren", ex: "Ik wil Nederlands leren." },
      { uk: "практикувати", nl: "oefenen", ex: "Ik oefen elke dag Nederlands." },
      { uk: "питання", nl: "vraag", ex: "Ik heb een vraag." },
      { uk: "відповідь", nl: "antwoord", ex: "Dank u voor uw antwoord." },
    ],
  },
  {
    id: "work",
    title: "Робота",
    nlTitle: "Werk",
    cards: [
      { uk: "робота", nl: "werk", ex: "Ik heb veel werk." },
      { uk: "працювати", nl: "werken", ex: "Ik werk in Amsterdam." },
      { uk: "начальник", nl: "baas", ex: "Mijn baas is vriendelijk." },
      { uk: "колега", nl: "collega", ex: "Mijn collega helpt mij." },
      { uk: "офіс", nl: "kantoor", ex: "Het kantoor is groot." },
      { uk: "ресторан", nl: "restaurant", ex: "Ik werk in een restaurant." },
      { uk: "магазин", nl: "winkel", ex: "Zij werkt in een winkel." },
      { uk: "фабрика", nl: "fabriek", ex: "Mijn broer werkt in een fabriek." },
      { uk: "механік", nl: "monteur", ex: "Omar is monteur." },
      { uk: "прибиральник", nl: "schoonmaker", ex: "De schoonmaker werkt hard." },
      { uk: "кухар", nl: "kok", ex: "Mijn vader is kok." },
      { uk: "продавець", nl: "verkoper", ex: "Hij werkt als verkoper." },
      { uk: "досвід", nl: "ervaring", ex: "Ik heb veel ervaring." },
      { uk: "робочий день", nl: "werkdag", ex: "Mijn werkdag begint om acht uur." },
      { uk: "зустріч", nl: "afspraak", ex: "Wij hebben een afspraak." },
      { uk: "коробка", nl: "doos", ex: "Ik draag zware dozen." },
      { uk: "ключі", nl: "sleutels", ex: "Ik ben mijn sleutels kwijt." },
      { uk: "велосипед", nl: "fiets", ex: "Ik ga met de fiets naar werk." },
      { uk: "автомобіль", nl: "auto", ex: "Mijn auto is kapot." },
      { uk: "аварія", nl: "ongeluk", ex: "Ik had een ongeluk." },
      { uk: "страхування", nl: "verzekering", ex: "De verzekering helpt mij." },
      { uk: "ремонт", nl: "reparatie", ex: "Mijn fiets heeft reparatie nodig." },
      { uk: "прибирати", nl: "schoonmaken", ex: "Ik moet het kantoor schoonmaken." },
      { uk: "замовлення", nl: "bestelling", ex: "De bestelling is niet compleet." },
      { uk: "доставляти", nl: "bezorgen", ex: "Wij bezorgen eten." },
    ],
  },
  {
    id: "health",
    title: "Здоров'я",
    nlTitle: "Gezondheid",
    cards: [
      { uk: "хворий", nl: "ziek", ex: "Ik ben ziek." },
      { uk: "лікар", nl: "dokter", ex: "Ik ga naar de dokter." },
      { uk: "сімейний лікар", nl: "huisarts", ex: "Ik zoek een huisarts." },
      { uk: "лікарня", nl: "ziekenhuis", ex: "Hij ligt in het ziekenhuis." },
      { uk: "фізіотерапевт", nl: "fysiotherapeut", ex: "Ik ga naar de fysiotherapeut." },
      { uk: "ліки", nl: "medicijnen", ex: "Ik gebruik medicijnen." },
      { uk: "застуда", nl: "verkoudheid", ex: "Ik heb een verkoudheid." },
      { uk: "кашель", nl: "hoest", ex: "Ik heb veel hoest." },
      { uk: "температура", nl: "koorts", ex: "Ik heb koorts." },
      { uk: "біль", nl: "pijn", ex: "Ik heb pijn." },
      { uk: "біль у спині", nl: "rugpijn", ex: "Ik heb rugpijn." },
      { uk: "зламана нога", nl: "gebroken been", ex: "Hij heeft een gebroken been." },
      { uk: "почуватися погано", nl: "zich niet goed voelen", ex: "Ik voel mij niet goed." },
      { uk: "втомлений", nl: "moe", ex: "Ik ben moe." },
      { uk: "аптека", nl: "apotheek", ex: "Ik ga naar de apotheek." },
    ],
  },
  {
    id: "home",
    title: "Житло і район",
    nlTitle: "Huis en buurt",
    cards: [
      { uk: "будинок", nl: "huis", ex: "Ik woon in een groot huis." },
      { uk: "квартира", nl: "appartement", ex: "Mijn appartement is klein." },
      { uk: "кухня", nl: "keuken", ex: "Mijn keuken is modern." },
      { uk: "кімната", nl: "kamer", ex: "Wij hebben vier kamers." },
      { uk: "спальня", nl: "slaapkamer", ex: "Mijn slaapkamer is rustig." },
      { uk: "ванна кімната", nl: "badkamer", ex: "De badkamer is schoon." },
      { uk: "сусід", nl: "buurman", ex: "Mijn buurman is aardig." },
      { uk: "сусідка", nl: "buurvrouw", ex: "Mijn buurvrouw helpt mij vaak." },
      { uk: "район", nl: "buurt", ex: "Mijn buurt is mooi." },
      { uk: "парк", nl: "park", ex: "Ik wandel in het park." },
      { uk: "природа", nl: "natuur", ex: "Ik hou van de natuur." },
      { uk: "переїжджати", nl: "verhuizen", ex: "Wij gaan verhuizen." },
      { uk: "шум", nl: "lawaai", ex: "Mijn buurman maakt lawaai." },
      { uk: "вечірка", nl: "feest", ex: "Wij organiseren een feest." },
      { uk: "вулиця", nl: "straat", ex: "Mijn straat is rustig." },
      { uk: "сад", nl: "tuin", ex: "Wij hebben een kleine tuin." },
    ],
  },
  {
    id: "family",
    title: "Сім'я та діти",
    nlTitle: "Familie en kinderen",
    cards: [
      { uk: "сім'я", nl: "familie", ex: "Mijn familie woont in Oekraïne." },
      { uk: "дитина", nl: "kind", ex: "Mijn kind gaat naar school." },
      { uk: "діти", nl: "kinderen", ex: "De kinderen spelen buiten." },
      { uk: "син", nl: "zoon", ex: "Mijn zoon is zeven jaar oud." },
      { uk: "донька", nl: "dochter", ex: "Mijn dochter houdt van muziek." },
      { uk: "чоловік", nl: "man", ex: "Mijn man werkt veel." },
      { uk: "дружина", nl: "vrouw", ex: "Mijn vrouw kookt graag." },
      { uk: "няня", nl: "oppas", ex: "Wij zoeken een oppas." },
      { uk: "народження", nl: "geboorte", ex: "De geboorte van de baby is mooi." },
      { uk: "дитина народилася", nl: "baby geboren", ex: "Er is een baby geboren." },
      { uk: "батьки", nl: "ouders", ex: "Mijn ouders wonen in Polen." },
    ],
  },
  {
    id: "food",
    title: "Їжа та покупки",
    nlTitle: "Eten en boodschappen",
    cards: [
      { uk: "їжа", nl: "eten", ex: "Ik hou van lekker eten." },
      { uk: "готувати", nl: "koken", ex: "Mijn moeder kookt elke dag." },
      { uk: "страва", nl: "gerecht", ex: "Pasta is mijn favoriete gerecht." },
      { uk: "хліб", nl: "brood", ex: "Ik eet brood in de ochtend." },
      { uk: "сир", nl: "kaas", ex: "Nederlandse kaas is lekker." },
      { uk: "м'ясо", nl: "vlees", ex: "Ik eet niet veel vlees." },
      { uk: "овочі", nl: "groenten", ex: "Groenten zijn gezond." },
      { uk: "напій", nl: "drankje", ex: "Ik drink graag koffie." },
      { uk: "супермаркет", nl: "supermarkt", ex: "Ik koop eten in de supermarkt." },
      { uk: "ціна", nl: "prijs", ex: "De prijs is goed." },
      { uk: "сайт", nl: "website", ex: "De website werkt goed." },
    ],
  },
  {
    id: "leisure",
    title: "Вільний час",
    nlTitle: "Vrije tijd",
    cards: [
      { uk: "музика", nl: "muziek", ex: "Ik luister graag naar muziek." },
      { uk: "футбол", nl: "voetbal", ex: "Ik kijk graag naar voetbal." },
      { uk: "квитки", nl: "kaartjes", ex: "Ik heb kaartjes voor de wedstrijd." },
      { uk: "свято", nl: "feest", ex: "Het feest was leuk." },
      { uk: "відпустка", nl: "vakantie", ex: "Wij waren op vakantie in Spanje." },
      { uk: "додаток", nl: "app", ex: "Ik gebruik deze app elke dag." },
      { uk: "фотоальбом", nl: "fotoboek", ex: "Ik maak een fotoboek." },
      { uk: "книга", nl: "boek", ex: "Ik lees graag boeken." },
      { uk: "фільм", nl: "film", ex: "Wij kijken een film." },
      { uk: "співати", nl: "zingen", ex: "Mijn buurvrouw zingt mooi." },
      { uk: "танцювати", nl: "dansen", ex: "Wij dansen op het feest." },
      { uk: "гуляти", nl: "wandelen", ex: "Ik wandel graag in het park." },
      { uk: "подорожувати", nl: "reizen", ex: "Ik wil naar Italië reizen." },
    ],
  },
  {
    id: "verbs",
    title: "Найважливіші дієслова",
    nlTitle: "Belangrijkste werkwoorden",
    cards: [
      { uk: "бути", nl: "zijn", ex: "Ik ben moe." },
      { uk: "мати", nl: "hebben", ex: "Ik heb een probleem." },
      { uk: "йти", nl: "gaan", ex: "Ik ga naar school." },
      { uk: "приходити", nl: "komen", ex: "Ik kom morgen." },
      { uk: "працювати", nl: "werken", ex: "Ik werk veel." },
      { uk: "вчитися", nl: "leren", ex: "Ik leer Nederlands." },
      { uk: "писати", nl: "schrijven", ex: "Ik schrijf een e-mail." },
      { uk: "дзвонити", nl: "bellen", ex: "Ik bel mijn collega." },
      { uk: "жити", nl: "wonen", ex: "Ik woon in Utrecht." },
      { uk: "їсти", nl: "eten", ex: "Wij eten samen." },
      { uk: "пити", nl: "drinken", ex: "Ik drink koffie." },
      { uk: "купувати", nl: "kopen", ex: "Ik koop een fiets." },
      { uk: "допомагати", nl: "helpen", ex: "Mijn vriend helpt mij." },
      { uk: "шукати", nl: "zoeken", ex: "Ik zoek een oppas." },
      { uk: "брати", nl: "nemen", ex: "Neem je laptop mee." },
      { uk: "давати", nl: "geven", ex: "Ik geef het morgen terug." },
      { uk: "позичати", nl: "lenen", ex: "Mag ik jouw fiets lenen?" },
      { uk: "знаходити", nl: "vinden", ex: "Ik kan mijn sleutels niet vinden." },
      { uk: "забувати", nl: "vergeten", ex: "Ik vergeet mijn tas vaak." },
      { uk: "чекати", nl: "wachten", ex: "Ik wacht op de bus." },
      { uk: "говорити", nl: "praten", ex: "Kunnen we praten?" },
      { uk: "везти", nl: "brengen", ex: "Ik breng de doos morgen." },
      { uk: "забирати", nl: "ophalen", ex: "Ik haal Omar om acht uur op." },
      { uk: "починати", nl: "beginnen", ex: "De cursus begint maandag." },
      { uk: "закінчувати", nl: "eindigen", ex: "Mijn werk eindigt om vijf uur." },
      { uk: "використовувати", nl: "gebruiken", ex: "Ik gebruik mijn telefoon elke dag." },
      { uk: "заповнювати", nl: "invullen", ex: "Ik vul het formulier in." },
      { uk: "надсилати", nl: "sturen", ex: "Ik stuur een e-mail." },
    ],
  },
];
